=== LorettaDevs/Loretta/src/Compilers/Lua/Portable/Syntax/Syntax.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--suppress XmlDefaultAttributeValue (justification: readability) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Tree" type="TreeType"/>
    <xs:complexType name="TreeType">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="NodeType" name="Node"/>
            <xs:element type="BaseNodeType" name="AbstractNode"/>
            <xs:element type="BaseNodeType" name="PredefinedNode"/>
        </xs:choice>
        <xs:attribute type="xs:string" name="Root"/>
    </xs:complexType>
    <xs:complexType name="BaseNodeType">
        <xs:sequence>
            <xs:element type="Comment" name="TypeComment" maxOccurs="1" minOccurs="0"/>
            <xs:element type="Comment" name="FactoryComment" maxOccurs="1" minOccurs="0"/>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element type="FieldType" name="Field"/>
                <xs:element type="ChoiceType" name="Choice"/>
                <xs:element type="SequenceType" name="Sequence"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute type="xs:string" name="Base" use="required"/>
        <xs:attribute type="xs:string" name="Name" use="required"/>
        <xs:attribute type="xs:boolean" name="SkipConvenienceFactories" use="optional"/>
    </xs:complexType>
    <xs:complexType name="NodeType">
        <xs:sequence>
            <xs:element type="Comment" name="TypeComment" maxOccurs="1" minOccurs="0"/>
            <xs:element type="Comment" name="FactoryComment" maxOccurs="1" minOccurs="0"/>
            <xs:element type="KindType" name="Kind" maxOccurs="unbounded"/>
            <xs:choice maxOccurs="unbounded" minOccurs="1">
                <xs:element type="FieldType" name="Field"/>
                <xs:element type="ChoiceType" name="Choice"/>
                <xs:element type="SequenceType" name="Sequence"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute type="xs:string" name="Base" use="required"/>
        <xs:attribute type="xs:string" name="Name" use="required"/>
        <xs:attribute type="xs:boolean" name="SkipConvenienceFactories" use="optional"/>
    </xs:complexType>
    <xs:complexType name="Comment">
        <xs:sequence>
            <xs:element type="xs:all" name="summary" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:all" name="remarks" maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ChoiceType">
        <xs:choice>
            <xs:element type="FieldType" name="Field" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="SequenceType" name="Sequence" maxOccurs="unbounded" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="SequenceType">
        <xs:choice>
            <xs:element type="FieldType" name="Field" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="ChoiceType" name="Choice" maxOccurs="unbounded" minOccurs="0"/>
        </xs:choice>
        <xs:attribute type="xs:boolean" name="Optional" use="optional"/>
    </xs:complexType>
    <xs:complexType name="FieldType">
        <xs:sequence>
            <xs:element type="Comment" name="PropertyComment" maxOccurs="1" minOccurs="0"/>
            <xs:element type="KindType" name="Kind" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="Name" use="required"/>
        <xs:attribute type="xs:string" name="Type" use="required"/>
        <xs:attribute type="xs:boolean" name="AllowTrailingSeparator" use="optional"/>
        <xs:attribute type="xs:boolean" name="FactoryRequired" use="optional"/>
        <xs:attribute type="xs:nonNegativeInteger" name="MinCount" use="optional"/>
        <xs:attribute type="xs:boolean" name="New" use="optional"/>
        <xs:attribute type="xs:boolean" name="Optional" use="optional"/>
        <xs:attribute type="xs:boolean" name="Override" use="optional"/>
    </xs:complexType>
    <xs:complexType name="KindType">
        <xs:attribute type="xs:string" name="Name" use="required"/>
    </xs:complexType>
</xs:schema>

=== LorettaDevs/Loretta/src/Compilers/Lua/Portable/Syntax/Syntax.xml
<?xml version="1.0" encoding="utf-8" ?>
<Tree xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Syntax.xsd"
      Root="SyntaxNode">

    <PredefinedNode Name="LuaSyntaxNode" Base="SyntaxNode"/>
    <PredefinedNode Name="SyntaxToken" Base="LuaSyntaxNode"/>
    <PredefinedNode Name="StructuredTriviaSyntax" Base="LuaSyntaxNode"/>

    <!-- Structured Trivia -->

    <Node Name="SkippedTokensTriviaSyntax" Base="StructuredTriviaSyntax">
        <Kind Name="SkippedTokensTrivia"/>
        <Field Name="Tokens" Type="SyntaxList&lt;SyntaxToken&gt;"/>
    </Node>

    <!-- Statement List -->
    <Node Name="StatementListSyntax" Base="LuaSyntaxNode">
        <TypeComment>
            <summary>Represents a block of code.</summary>
        </TypeComment>
        <FactoryComment>
            <summary>Creates a new
                <see cref="StatementListSyntax"/>
                node.
            </summary>
        </FactoryComment>
        <Kind Name="StatementList"/>
        <Field Name="Statements" Type="SyntaxList&lt;StatementSyntax&gt;">
            <PropertyComment>
                <summary>The list of statements contained within this block.</summary>
            </PropertyComment>
        </Field>
    </Node>

    <!-- Parameters -->

    <AbstractNode Name="ParameterSyntax" Base="LuaSyntaxNode">
        <TypeComment>
            <summary>The base type for parameter nodes.</summary>
        </TypeComment>
    </AbstractNode>

    <Node Name="NamedParameterSyntax" Base="ParameterSyntax">
        <TypeComment>
            <summary>Represents a named function parameter.</summary>
        </TypeComment>
        <FactoryComment>
            <summary>Creates a new
                <see cref="NamedParameterSyntax"/>
                node.
            </summary>
        </FactoryComment>
        <Kind Name="NamedParameter"/>
        <Field Name="Identifier" Type="SyntaxToken">
            <PropertyComment>
                <summary>The name of the parameter.</summary>
            </PropertyComment>
            <Kind Name="IdentifierToken"/>
        </Field>
        <Field Name="TypeBinding" Type="TypeBindingSyntax" Optional="true">
            <PropertyComment>
                <summary>The
                    <see cref="TypeBindingSyntax"/>
                    containing the (optional) type.
                </summary>
            </PropertyComment>
            <Kind Name="TypeBinding"/>
        </Field>
    </Node>

    <Node Name="VarArgParameterSyntax" Base="ParameterSyntax">
        <TypeComment>
            <summary>Represents a vararg function parameter.</summary>
        </TypeComment>
        <FactoryComment>
            <summary>Creates a new
                <see cref="VarArgParameterSyntax"/>
                node.
            </summary>
        </FactoryComment>
        <Kind Name="VarArgParameter"/>
        <Field Name="VarArgToken" Type="SyntaxToken">
            <PropertyComment>
                <summary>The vararg token.</summary>
            </PropertyComment>
            <Kind Name="DotDotDotToken"/>
        </Field>
        <Field Name="TypeBinding" Type="TypeBindingSyntax" Optional="true">
            <PropertyComment>
                <summary>The
                    <see cref="TypeBindingSyntax"/>
                    containing the (optional) type.
                </summary>
            </PropertyComment>
            <Kind Name="TypeBinding"/>
        </Field>
    </Node>

    <Node Name="ParameterListSyntax" Base="LuaSyntaxNode">
        <TypeComment>
            <summary>Represents a function declaration's parameter list.</summary>
        </TypeComment>
        <FactoryComment>
            <summary>Creates a new
                <see cref="ParameterListSyntax"/>
                node.
            </summary>
        </FactoryComment>
        <Kind Name="ParameterList"/>
        <Field Name="OpenParenthesisToken" Type="SyntaxToken">
            <PropertyComment>
                <summary>The parameter list opening parenthesis.</summary>
            </PropertyComment>
            <Kind Name="OpenParenthesisToken"/>
        </Field>
        <Field Name="Parameters" Type="SeparatedSyntaxList&lt;ParameterSyntax&gt;">
            <PropertyComment>
                <summary>The parameter list opening parenthesis.</summary>
            </PropertyComment>
        </Field>
        <Field Name="CloseParenthesisToken" Type="SyntaxToken">
            <PropertyComment>
                <summary>The close parenthesis token.</summary>
            </PropertyComment>
            <Kind Name="CloseParenthesisToken"/>
        </Field>
    </Node>

    <!-- Table Fields -->

    <AbstractNode Name="TableFieldSyntax" Base="LuaSyntaxNode">
        <TypeComment>
            <summary>The base class for table fields.</summary>
        </TypeComment>
    </AbstractNode>

    <Node Name="IdentifierKeyedTableFieldSyntax" Base="TableFieldSyntax">
        <TypeComment>
            <summary>Represents a table field whose key is an identifier.</summary>
        </TypeComment>
        <FactoryComment>
            <summary>Creates a new
                <see cref="IdentifierKeyedTableFieldSyntax"/>
                node.
            </summary>
        </FactoryComment>
        <Kind Name="IdentifierKeyedTableField"/>
        <Field Name="Identifier" Type="SyntaxToken">
            <PropertyComment>
                <summary>The table field's key.</summary>
            </PropertyComment>
            <Kind Name="IdentifierToken"/>
        </Field>
        <Field Name="EqualsToken" Type="SyntaxToken">
            <PropertyComment>
                <summary>The equals token.</summary>
            </PropertyComment>
            <Kind Name="EqualsToken"/>
        </Field>
        <Field Name="Value" Type="ExpressionSyntax">
            <PropertyComment>
                <summary>The table field's value.</summary>
            </PropertyComment>
        </Field>
    </Node>

    <Node Name="ExpressionKeyedTableFieldSyntax" Base="TableFieldSyntax">
        <TypeComment>
            <summary>Represents a table field whose key is an expression.</summary>
        </TypeComment>
        <FactoryComment>
            <summary>Creates a new
                <see cref="ExpressionKeyedTableFieldSyntax"/>
                node.
            </summary>
        </FactoryComment>
        <Kind Name="ExpressionKeyedTableField"/>
        <Field Name="OpenBracketToken" Type="SyntaxToken">
            <PropertyComment>
                <summary>The opening bracket token.</summary>
            </PropertyComment>
            <Kind Name="OpenBracketToken"/>
        </Field>
        <Field Name="Key" Type="ExpressionSyntax">
            <PropertyComment>
                <summary>The table field's key.</summary>
            </PropertyComment>
        </Field>
        <Field Name="CloseBracketToken" Type="SyntaxToken">
            <PropertyComment>
                <summary>The closing bracket token.</summary>
            </PropertyComment>
            <Kind Name="CloseBracketToken"/>
        </Field>
        <Field Name="EqualsToken" Type="SyntaxToken">
            <PropertyComment>
                <summary>The equals token.</summary>
            </PropertyComment>
            <Kind Name="EqualsToken"/>
        </Field>
        <Field Name="Value" Type="ExpressionSyntax">
            <PropertyComment>
                <summary>The field's value.</summary>
            </PropertyComment>
        </Field>
    </Node>

    <Node Name="UnkeyedTableFieldSyntax" Base="TableFieldSyntax">
        <TypeComment>
            <summary>Represents a table field without a key.</summary>
        </TypeComment>
        <FactoryComment>
            <summary>Creates a new
                <see cref="UnkeyedTableFieldSyntax"/>
                node.
            </summary>
        </FactoryComment>
        <Kind Name="UnkeyedTableField"/>
        <Field Name="Value" Type="ExpressionSyntax">
            <PropertyComment>
                <summary>The table field's value.</summary>
            </PropertyComment>
        </Field>
    </Node>

    <!-- Function Names -->

    <AbstractNode Name="FunctionNameSyntax" Base="LuaSyntaxNode">
        <TypeComment>
            <summary>The base class for function name nodes.</summary>
        </TypeComment>
        <Field Name="Name" Type="SyntaxToken">
            <PropertyComment>
                <summary>The member name.</summary>
            </PropertyComment>
            <Kind Name="IdentifierToken"/>
        </Field>
    </AbstractNode>

    <Node Name="SimpleFunctionNameSyntax" Base="FunctionNameSyntax">
        <TypeComment>
            <summary>Represents a function name which is only an identifier.</summary>
        </TypeComment>
        <FactoryComment>
            <summary>Creates a new
                <see cref="SimpleFunctionNameSyntax"/>
                node.
            </summary>
        </FactoryComment>
        <Kind Name="SimpleFunctionName"/>
        <Field Name="Name" Type="SyntaxToken" Override="true">
            <PropertyComment>
                <summary>The function name.</summary>
            </PropertyComment>
            <Kind Name="IdentifierToken"/>
        </Field>
    </Node>

    <Node Name="MemberFunctionNameSyntax" Base="FunctionNameSyntax">
        <TypeComment>
            <summary>Represents a function name which is a member.</summary>
        </TypeComment>
        <FactoryComment>
            <summary>Creates a new
                <see cref="MemberFunctionNameSyntax"/>
                node.
            </summary>
        </FactoryComment>
        <Kind Name="MemberFunctionName"/>
        <Field Name="BaseName" Type="FunctionNameSyntax">
            <PropertyComment>
                <summary>The base function name.</summary>
            </PropertyComment>
        </Field>
        <Field Name="DotToken" Type="SyntaxToken">
            <PropertyComment>
